# Generated by Django 3.2.4 on 2021-08-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_rename_organization_id_agent_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='organization',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
